2025-10-26 13:20:07.99
9b92a589
User
2025-10-26 12:20:07,989 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8096451897:AAE8ZbLLbh6NfP7RBIxs4GIAH0vOBWSffb0/getUpdates "HTTP/1.1 409 Conflict"
2025-10-26 13:20:07.99
9b92a589
User
2025-10-26 12:20:07,991 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
2025-10-26 13:20:07.99
9b92a589
User
Traceback (most recent call last):
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 134, in network_retry_loop
2025-10-26 13:20:07.99
9b92a589
User
await do_action()
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 127, in do_action
2025-10-26 13:20:07.99
9b92a589
User
action_cb_task.result()
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_updater.py", line 340, in polling_action_cb
2025-10-26 13:20:07.99
9b92a589
User
updates = await self.bot.get_updates(
2025-10-26 13:20:07.99
9b92a589
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 676, in get_updates
2025-10-26 13:20:07.99
9b92a589
User
updates = await super().get_updates(
2025-10-26 13:20:07.99
9b92a589
User
^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/_bot.py", line 4780, in get_updates
2025-10-26 13:20:07.99
9b92a589
User
await self._post(
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/_bot.py", line 703, in _post
2025-10-26 13:20:07.99
9b92a589
User
return await self._do_post(
2025-10-26 13:20:07.99
9b92a589
User
^^^^^^^^^^^^^^^^^^^^
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 372, in _do_post
2025-10-26 13:20:07.99
9b92a589
User
return await super()._do_post(
2025-10-26 13:20:07.99
9b92a589
User
^^^^^^^^^^^^^^^^^^^^^^^
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/_bot.py", line 732, in _do_post
2025-10-26 13:20:07.99
9b92a589
User
result = await request.post(
2025-10-26 13:20:07.99
9b92a589
User
^^^^^^^^^^^^^^^^^^^
2025-10-26 13:20:07.99
9b92a589
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 198, in post
2025-10-26 13:20:07.99
9b92a589
User
result = await self._request_wrapper(
2025-10-26 13:20:07.99
9b92a589
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
